import type { NextPage } from "next";
import Head from "next/head";
import Header from "../Components/Header/index";
import Started from "../Components/Started/index";
import UrlGenerator from "../Components/UrlGenerator/index";
import Infos from "../Components/Infos/index";
import BoostLinks from "../Components/BoostLinks/index";
import Footer from "../Components/Footer/index";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <Header />
      <main>
        <Started />
        <UrlGenerator />
        <Infos />
        <BoostLinks />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
